apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: springboot-cluster
  region: eu-central-1         # e.g. eu-central-1
  version: "1.35"

iam:
  withOIDC: true              # enables IRSA for service accounts

managedNodeGroups:
  - name: node-group
    instanceType: t3.medium
    minSize: 1
    maxSize: 6
    desiredCapacity: 1
    amiFamily: AmazonLinux2023
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

accessConfig:
  authenticationMode: API_AND_CONFIG_MAP
  accessEntries:
    - principalARN: arn:aws:iam::762948750421:user/eks-cluster
      type: STANDARD
      accessPolicies:
        - policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
          accessScope:
            type: cluster
